'use strict';

/**
 * The Eifeler Regel (n-rule), driven by LOD's own flags rather than by
 * anything the model believes about Luxembourgish.
 *
 * How the flags work. In the LOD search index every entry lists its spellings,
 * and the n-dropped variant carries `reason="n-rule"`:
 *
 *   <spelling suggest="true">Aen</spelling>
 *   <spelling suggest="false" reason="n-rule">Ae</spelling>
 *
 * So a word W ending in -n is *subject* to the rule exactly when W minus its
 * final n is a flagged form. That is what separates "Aen" (subject) from
 * "wann", "hunn", "situatioun", "terrain" (not subject - the n is stem-final).
 * Deriving subjecthood from the flags instead of from spelling is what keeps
 * the loan words and the double-n words out of the results.
 *
 * The trigger set below was measured, not recalled. Over the 454,501 adjacent
 * word pairs in LOD's 59,019 example sentences, the share of pairs whose first
 * word ends in -n splits cleanly by the following letter:
 *
 *   d 33.3%  t 38.1%  z 28.5%  n 24.1%  h 26.0%  + vowels 23-35%
 *   s 5.6%   w 6.9%   f 4.8%   v 4.5%   m 2.9%   g 2.7%  b 1.8%  l 1.1%
 *
 * i.e. n/d/t/z/h and vowels keep the n, everything else drops it. See
 * `docs/n-rule-evidence.md` for the full table and how to reproduce it.
 */

const TRIGGER_CONSONANTS = new Set(['n', 'd', 't', 'z', 'h']);
const VOWELS = new Set('aeiouäëéèöüáàâêîôûy'.split(''));

/** Does this following-word start a context that keeps the preceding -n? */
function startsTrigger(word) {
  const first = String(word)[0];
  if (!first) return false;
  const lower = first.toLowerCase();
  return TRIGGER_CONSONANTS.has(lower) || VOWELS.has(lower);
}

/**
 * The rule is about sound, not spelling, and for some tokens the written first
 * character does not tell us the sound:
 *
 *  - initialisms are read as letter names - LOD writes "hiren CV" (/tseː…/),
 *    "en aneren CD", "den S";
 *  - numerals are read as words - "20" is "zwanzeg", so it triggers on z;
 *  - a bare letter is its own name.
 *
 * We cannot resolve these without a pronunciation, so the checker skips them
 * instead of guessing. Skipping is the safe direction: a missed warning costs
 * less than a false failure that trains the wrong form.
 */
function hasOpaqueOnset(word) {
  const value = String(word);
  if (value === '') return true;
  if (/^[\d]/.test(value)) return true; // numeral, read aloud
  const bare = value.replace(/[^\p{L}]/gu, '');
  if (bare === '') return true;
  if (bare.length === 1) return true; // letter name
  if (bare.length <= 4 && bare === bare.toUpperCase()) return true;
  // An initialism that has grown an ending or a compound tail is still read as
  // letter names at the front: "CDen", "CD-Player", "SNCF-Streck".
  return /^\p{Lu}{2,4}(?![\p{Lu}])/u.test(value);
}

/**
 * Builds a checker from the corpus lexicon.
 *
 * `nRuleForms` - the set of n-dropped forms flagged `reason="n-rule"`.
 * `retentionExceptions` - following-tokens where LOD's own corpus keeps the
 *   final n often enough that a hard failure would be wrong (`sech`, `se`,
 *   loan words with /dʒ/ or /tʃ/ onsets like `job`, `challenge`). Generated by
 *   build-corpus.js from the example sentences, so it is data, not opinion.
 */
function createChecker({ nRuleForms, retentionExceptions }) {
  const flagged = nRuleForms instanceof Set ? nRuleForms : new Set(nRuleForms);
  const exceptions = retentionExceptions instanceof Set ? retentionExceptions : new Set(retentionExceptions || []);

  const isDroppedForm = (value) => flagged.has(value.toLowerCase());
  const isFullForm = (value) => {
    const lower = value.toLowerCase();
    return lower.endsWith('n') && flagged.has(lower.slice(0, -1));
  };

  /**
   * Checks one sentence's tokens (from lux-text.tokenise).
   *
   * Returns findings `{ severity, code, token, next, message }`.
   *
   * Severities, and why they differ:
   *  - `error` for an -n kept before a non-trigger. Measured against LOD's own
   *    sentences this direction is unambiguous once the exception list is
   *    applied.
   *  - `warning` for an n dropped before a trigger. That direction collides
   *    with homographs - "A" the noun vs "a" the dropped form of "an", "Wee"
   *    the noun vs "wee(n)" - and fails on 2.9% of LOD's own gold sentences,
   *    which is too noisy to gate a build on.
   */
  function checkTokens(tokens) {
    const findings = [];
    for (let i = 0; i < tokens.length; i += 1) {
      const token = tokens[i];
      const next = tokens[i + 1];
      if (!next || token.pauseAfter) continue; // a pause suspends the sandhi
      if (token.isClitic) continue;

      const following = next.clitic ? next.clitic : next.value;

      if (isFullForm(token.value)) {
        if (startsTrigger(following)) continue;
        if (hasOpaqueOnset(next.value)) continue;
        const severity = exceptions.has(next.value.toLowerCase()) ? 'warning' : 'error';
        findings.push({
          severity,
          code: 'n-rule/keep',
          token: token.raw,
          next: next.raw,
          message:
            severity === 'error'
              ? `"${token.raw}" should drop its final n before "${next.raw}" (Eifeler Regel): write "${token.value.slice(0, -1)}"`
              : `"${token.raw}" before "${next.raw}": LOD attests both the kept and the dropped n here - check by ear`,
        });
        continue;
      }

      if (isDroppedForm(token.value) && !token.value.toLowerCase().endsWith('n')) {
        if (!startsTrigger(following)) continue;
        if (hasOpaqueOnset(next.value)) continue;
        findings.push({
          severity: 'warning',
          code: 'n-rule/drop',
          token: token.raw,
          next: next.raw,
          message: `"${token.raw}" may need its final n before "${next.raw}" (Eifeler Regel) - unless it is a different word with the same spelling`,
        });
      }
    }
    return findings;
  }

  return { checkTokens, isDroppedForm, isFullForm };
}

module.exports = { createChecker, startsTrigger, hasOpaqueOnset, TRIGGER_CONSONANTS, VOWELS };
