/**
 * Mistakes — the cards you have got wrong, until you get them right.
 *
 * Benchmarked from Duolingo's Practice Hub, which collects your errors into a
 * named list you can go and clear. The insight worth copying is not the
 * scheduling — the Leitner box already puts a missed card at the front of the
 * queue, and does it better than a flat list would. It is that a learner wants
 * something **finite and completable**: "these 14, and then you are done" is a
 * different offer from "the algorithm will get to them", and only one of them
 * is a thing you can decide to do this evening.
 *
 * So this is a view over mistakes, not a second scheduler. Nothing here
 * changes when a word is next due; answering correctly removes the row, which
 * is the only way the list ever shrinks.
 *
 * A session drawn from here is graded like any other — the engine writes to the
 * same Leitner rows — but the plan is built from the mistake list rather than
 * from what is due, so it can be practised on demand and even when nothing is
 * scheduled.
 */

import { el, screenHead, button, plural } from '../dom.js';
import { Amelie } from '../amelie.js';
import { loadVocab, loadVerbs, loadPhrases, loadGrammar } from '../content.js';
import { listMistakes, getLearnDeckStates, STRANDS } from '../store.js';
import { DECKS, isDrillable, boxIndex } from '../drill/cards.js';
import { runSession } from '../drill/engine.js';

const SESSION_SIZE = 12;

export async function render(root, { settings, navigate }) {
  const [vocab, verbs, phrases, grammar, mistakes] = await Promise.all([
    loadVocab(),
    loadVerbs(),
    loadPhrases(),
    loadGrammar(),
    listMistakes(settings.playerId),
  ]);

  const decks = {
    vocab: { deck: DECKS.vocab, items: vocab },
    verb: { deck: DECKS.verb, items: verbs },
    phrase: { deck: DECKS.phrase, items: phrases },
    grammar: { deck: DECKS.grammar, items: grammar },
  };
  const byId = new Map(
    Object.entries(decks).map(([id, { items }]) => [id, new Map(items.map((item) => [item.id, item]))]),
  );

  // A row whose item no longer exists — the decks are regenerated by the
  // pipeline and ids can go — is dropped rather than crashing the screen.
  const resolved = mistakes
    .map((row) => ({ row, item: byId.get(row.deck)?.get(row.itemId) ?? null }))
    .filter(({ row, item }) => item && isDrillable(item, row.deck));

  if (resolved.length === 0) return renderEmpty(root, { navigate, hadRows: mistakes.length > 0 });

  // Most-missed first: a card got wrong three times is the one worth the next
  // ten minutes, and it is also the one the learner remembers failing.
  resolved.sort((a, b) => (b.row.misses ?? 1) - (a.row.misses ?? 1));

  const [vocabStates, verbStates, phraseStates, grammarStates] = await Promise.all([
    getLearnDeckStates(settings.playerId, 'vocab'),
    getLearnDeckStates(settings.playerId, 'verb'),
    getLearnDeckStates(settings.playerId, 'phrase'),
    getLearnDeckStates(settings.playerId, 'grammar'),
  ]);
  const states = { vocab: vocabStates, verb: verbStates, phrase: phraseStates, grammar: grammarStates };

  const plan = resolved.slice(0, SESSION_SIZE).map(({ row, item }) => ({
    item,
    strand: row.strand === STRANDS.prod ? STRANDS.prod : STRANDS.recv,
    isNew: false,
    deck: decks[row.deck].deck,
    pool: decks[row.deck].items.filter((candidate) => isDrillable(candidate, row.deck)),
  }));

  const boxes = new Map();
  for (const [id, deckStates] of Object.entries(states)) boxIndex(id, deckStates, boxes);

  return runSession({
    root,
    plan,
    boxes,
    settings,
    navigate,
    title: 'Your mistakes',
    sub: `${plural(resolved.length, 'card')} to clear`,
    back: '#/learn',
    again: '#/mistakes',
  });
}

/**
 * Nothing to clear. Distinguishes "you have never got anything wrong" from
 * "you cleared them all", because the second is an achievement and the first
 * is just a new install.
 */
function renderEmpty(root, { navigate, hadRows }) {
  const amelie = new Amelie({ size: 'lg', bubble: true });
  amelie.el.classList.add('amelie--stack', 'amelie--hero');
  amelie.say(hadRows ? 'Nothing left in here. Everything you got wrong, you have since got right.' : 'Nothing here yet. Cards you get wrong collect here so you can clear them on purpose.', 'celebrating');

  root.append(
    screenHead({ title: 'Your mistakes', back: '#/learn' }),
    el(
      'div',
      { class: 'stack stack--lg', style: { paddingBlockStart: 'var(--s6)' } },
      amelie.el,
      button('Back to Learn', { variant: 'secondary', class: 'btn btn--secondary btn--block', onclick: () => navigate('#/learn') }),
    ),
  );
  return { destroy() {} };
}
